const DATA_TYPES = {
  increments: "increments",
  bigincrements: "bigIncrements",
  biginteger: "bigInteger",
  binary: "binary",
  boolean: "boolean",
  date: "date",
  char: "char",
  datetime: "datetime",
  decimal: "decimal",
  enum: "enu",
  float: "float",
  integer: "integer",
  json: "json",
  string: "string",
  text: "text",
  time: "time",
  timestamp: "timestamp",
  timestamps: "timestamps",
  uuid: "uuid",
};
